---
- hosts: pgservers
  tasks:
  - name: Instalar python3-pip
    ansible.builtin.apt:
      name: python3-pip
      state: present

  - name: Atualizar a lista de pacotes localmente
    become: yes
    ansible.builtin.apt:
      update_cache: yes

  - name: Instalar libpq-dev localmente
    become: yes
    ansible.builtin.apt:
      name: libpq-dev
      state: present

  - name: Instalar psycopg2-binary localmente
    become: yes  
    ansible.builtin.pip:
      name: psycopg2-binary
      state: present

  - name: Instalar psycopg2 localmente
    become: yes  
    ansible.builtin.pip:
      name: psycopg2
      state: present

  - name: Adicionando repositório oficial PG
    ansible.builtin.apt_repository:
     repo: "deb https://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release }}-pgdg main"
     state: present
     filename: pgdg

  - name: Importando a chave de assinatura do repositório
    ansible.builtin.apt_key:
      url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
      state: present

  - name: Instalando PostgreSQL
    apt:
      name: postgresql-{{ postgres_version }}
      state: present

  - name: Initializando PostgreSQL
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: Criando Database
    postgresql_db:
      name: "{{ database_name }}"
      state: present

  - name: Criando Users
    postgresql_user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      database: "{{ database_name }}"
      state: present
      login_host: "{{ network_address }}"
      login_user: "postgres"
      login_password: ""
    loop: "{{ users }}"

  - name: Ajuste Listen Addresses
    lineinfile:
      path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
      line: "listen_addresses = 'localhost, {{ network_address }}'"
      state: present

  - name: Restart PostgreSQL
    service:
      name: postgresql
      state: restarted