- name: Configuração dos servidores PostgreSQL
  hosts: pgservers
  become: yes
  tasks:
    - name: 1/12 - Atualizar a lista de pacotes 
      become: yes
      ansible.builtin.apt:
        update_cache: yes

    - name: 2/12 - Instalar libpq-dev 
      become: yes
      ansible.builtin.apt:
        name: libpq-dev
        state: present

    - name: 3/12 - Instalar psycopg2-binary 
      become: yes  
      ansible.builtin.pip:
        name: psycopg2-binary
        state: present

    - name: 4/12 - Instalar psycopg2 
      become: yes  
      ansible.builtin.pip:
        name: psycopg2
        state: present

    - name: 5/12 - Adicionando repositório oficial PG
      ansible.builtin.apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release }}-pgdg main"
        state: present
        filename: pgdg.list

    - name: 6/12 - Importando a chave de assinatura do repositório
      ansible.builtin.apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: 7/12 - Instalando PostgreSQL 16 nos servidores.
      apt:
        name: postgresql-16
        state: latest

    - name: 8/12 - Criando usuário caio.novelletto SUPERUSER
      postgresql_user:
        name: caio.novelletto
        password: OIUyh3n_bn3l!8an.S
        role_attr_flags: "CREATEDB,SUPERUSER"

    - name: 9/12 - Criando usuário cafecom.build NOSUPERUSER
      postgresql_user:
        name: cafecom.build
        password: KiK0_891.1uiAHSG3_O
        role_attr_flags: "CREATEDB,NOSUPERUSER"

    - name: 10/12 - Criando database uat_app
      postgresql_schema:
        db: uat_app
        name: public
        owner: caio.novelletto

    - name: 11/12 - Liberando acesso via pg_hba para usuário caio.novelletto no database uat_app na rede local
      postgresql_pg_hba:
        dest: /var/lib/postgres/data/pg_hba.conf
        contype: host
        users: caio.novelletto
        source: 192.168.2.0/24
        databases: uat_app
        method: password

    - name: 12/12 - Liberando porta 5432 no Iptables.
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 5432
        source: null
        jump: ACCEPT
