---

- name: 1 - Criando servidores web
  hosts: webservers
  tasks:
    - name: Check ultimate version nginx
      apt:
        name: nginx
        state: latest

    - name: 2 - Liberando porta 80 no Iptables
      hosts: webservers
      tasks:
        - iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 80
            source: 
            jump: ACCEPT

    - name: 3 - Liberando porta 443 no Iptables
      hosts: webservers
      tasks:
        - iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 443
            source: 
            jump: ACCEPT